### ISSUE TITLE
Graphical "documentation" / Milestone

### ISSUE THREAD

**Issue by rubyFeedback** [markshannon/faster-cpython#9]
Hey there,

Some ruby guys are watching this too; I found that via ruby-discussions. ;-)

Anyway! Evidently this all takes time to implement, but what I was wondering,
would it be possible for you guys to also add benchmarks, ideally graphical
ones, of what has been achieved effectively? Ideally of course reproducible
ones, but at this point all I care about would be fancy graphics to stare in awe
when the "scripting" languages unite - and beat down even on C! :P

**Comment by markshannon** [comment]
Good luck with speeding up Ruby. This might be what you are looking for: speed.python.org
